version: 2
worflows:
  build-dev:
    jobs:
      - build
      - request-testing:
          type: approval
          requires:
            - build
      - deploy-aws:
          requires:
            - request-testing
